default_language_version:
  python: python3.11
repos:
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.0
    hooks:
      - id: flake8
        args: [ --max-line-length=120, --max-complexity=10 ]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: [ '--maxkb=1000' ]
      - id: check-json
      - id: check-merge-conflict
      - id: detect-private-key